app: stori-csv
service: sls-stori-csv

frameworkVersion: "3"

provider:
  name: aws
  runtime: go1.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    DYNAMODB_TABLE: summary
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/summary"

useDotenv: true

functions:
  ping:
    handler: bin/main
    package:
      include:
        - ./bin/main
    events:
      - http:
          path: /ping
          method: GET

  transactions:
    handler: bin/main
    package:
      include:
        - ./bin/main
    events:
      - http:
          path: /transactions
          method: POST

  sendEmail:
    handler: bin/main
    package:
      include:
        - ./bin/main
    events:
      - http:
          path: /send-email
          method: POST

package:
  patterns:
    - "!*/**"
    - bin/main

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: "ApiGatewayRestApi"

    s3:
      Type: "AWS::S3::Bucket"
      Properties:
        BucketName: "stori-csv-${opt:stage, 'dev'}-files"
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: true
          RestrictPublicBuckets: false

    SummaryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: summary
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: "N"
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH # Partition key
          - AttributeName: user_id
            KeyType: RANGE # Sort key
        ProvisionedThroughput:
          ReadCapacityUnits: 5 # Adjust as needed
          WriteCapacityUnits: 5 # Adjust as needed
